# Generated by Django 4.1.5 on 2023-01-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_moviedesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedesc',
            name='castname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedesc',
            name='charactername',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedesc',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedesc',
            name='movieid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieName',
            field=models.CharField(max_length=100),
        ),
    ]
