# Generated by Django 4.1.5 on 2023-01-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_moviedesc_castname_moviedesc_charactername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieDuration',
            field=models.CharField(default='', max_length=100),
        ),
    ]
