# Generated by Django 4.1.5 on 2023-01-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_movie_movieduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedesc',
            name='movieid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.movie'),
        ),
    ]
