# Generated by Django 4.1.5 on 2023-01-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_moviedesc_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedesc',
            name='movieid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task.movie'),
        ),
    ]
