# Generated by Django 4.1.5 on 2023-01-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_moviedesc_movieid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviedialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogue', models.CharField(default='', max_length=100)),
                ('starttime', models.CharField(default='', max_length=100)),
                ('endtime', models.CharField(default='', max_length=100)),
                ('movieid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task.movie')),
            ],
        ),
    ]
