# Generated by Django 4.1.5 on 2023-01-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_rename_castid_moviedialogue_castnameid'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedesc',
            name='dialogue',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedesc',
            name='endtime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='moviedesc',
            name='starttime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Moviedialogue',
        ),
    ]
