# Generated by Django 4.1.5 on 2023-01-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_moviedesc_dialogue_moviedesc_endtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedesc',
            name='movieid',
        ),
    ]
