# Generated by Django 4.1.5 on 2023-01-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_remove_moviedesc_movieid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedesc',
            name='dialogue',
        ),
        migrations.RemoveField(
            model_name='moviedesc',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='moviedesc',
            name='starttime',
        ),
        migrations.AddField(
            model_name='moviedesc',
            name='movieid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task.movie'),
        ),
        migrations.CreateModel(
            name='Moviedialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogue', models.CharField(default='', max_length=100)),
                ('starttime', models.CharField(default='', max_length=100)),
                ('endtime', models.CharField(default='', max_length=100)),
                ('movieid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task.movie')),
            ],
        ),
    ]
