# Generated by Django 4.1.5 on 2023-01-16 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_moviedialogue_castnameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedialogue',
            name='castnameid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task.moviedesc'),
        ),
    ]
