# Generated by Django 4.1.5 on 2023-01-16 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_alter_moviedialogue_castnameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedesc',
            name='movieid',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='task.movie'),
        ),
        migrations.AlterField(
            model_name='moviedialogue',
            name='movieid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.movie'),
        ),
    ]
