# Generated by Django 4.1.5 on 2023-01-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_alter_moviedesc_movieid_alter_moviedialogue_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedialogue',
            name='castnameid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.moviedesc'),
        ),
    ]
