# Generated by Django 4.1.5 on 2023-01-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_alter_moviedialogue_castnameid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedialogue',
            name='castnameid',
        ),
    ]
