# Generated by Django 4.1.5 on 2023-01-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_remove_moviedialogue_castnameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedesc',
            name='movieid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task.movie'),
        ),
        migrations.AlterField(
            model_name='moviedialogue',
            name='movieid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='task.movie'),
        ),
    ]
